listenAddressSingleHTTPFrontend: 0.0.0.0:1337
actions:
  - title: Node Sync Status
    popupOnStart: execution-dialog-stdout-only
    shell: /etc/OliveTin/json-rpc/node/execute_owner.sh
    icon: ping
    timeout: 5

  - title: Grin Wallet Info
    popupOnStart: execution-dialog-stdout-only
    shell: ping localhost

dashboards:
  - title: All Processes
    contents:
      - title: Grin Node (Mainnet)
        type: fieldset
        contents:
        - title: Node Sync Status
      - type: fieldset
        title: Grin Wallet
        contents:
        - title: Grin Wallet Info