listenAddressSingleHTTPFrontend: 0.0.0.0:1337
actions:
  - title: Create Wallet
    popupOnStart: execution-dialog-stdout-only
    shell: node /etc/OliveTin/owner_api_client/src/create_wallet.js
    arguments:
      - name: wallet_password
        type: ascii_sentence
        description: Wallet Password
  - title: Wallet Summary Info
    popupOnStart: execution-dialog-stdout-only
    shell: node /etc/OliveTin/owner_api_client/src/wallet_info.js
    arguments:
      - name: wallet_password
        type: ascii_sentence
        description: Wallet Password
  - title: Wallet Txs
    popupOnStart: execution-dialog-stdout-only
    shell: node /etc/OliveTin/owner_api_client/src/wallet_txs.js
    arguments:
      - name: wallet_password
        type: ascii_sentence
        description: Wallet Password
  
dashboards:
  - title: Grin Wallet (Mainnet - Contracts)
    contents:
      - title: Create Wallet
        type: fieldset
        contents:
        - title: Create Wallet      
      - title: Info
        type: fieldset
        contents:
        - title: Wallet Summary Info
        - title: Wallet Txs
