services:
  grin-olivetin:
    build:
      context: ../../../
      dockerfile: base-olivetin/Dockerfile
      target: olivetin_grin_wallet_build
    image: grin-olivetin-mainnet 
    environment:
      - OWNER_API_PORT=3415
    volumes:
      - ../configs/mainnet/wallet.yaml:/etc/OliveTin/config.yaml
    ports:
      - "1337:1337"
    restart: unless-stopped